services:
  mysql:
    image: mysql:8
    container_name: luxora_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: luxora_db
      MYSQL_USER: luxora_user
      MYSQL_PASSWORD: luxora_password
    ports:
      - "3306:3306"
    volumes:
      - luxora_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  luxora_mysql_data:
    driver: local
